# Site settings
title: Qiyan's Blog
email: chunfantasy@gmail.com
description: "This is Qiyan's blog."
baseurl: ""
url: "http://qiyan.chun.no"

# Build settings
markdown: kramdown
permalink: /:year/:month/:title
paginate: 10
